services:

  postgres:
    image: postgres:18
    container_name: postgres-artemis

    environment:
      POSTGRES_DB: vaudoise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lambda

    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vaudoise"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


  jaeger:
    image: jaegertracing/all-in-one:latest

    ports:
      - "16686:16686"
      - "4317:4317"


  artemis:
    image: apache/artemis:latest
    container_name: artemis-broker

    ports:
      - "61616:61616"
      - "8161:8161"

    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin

    volumes:
      - ./src/main/resources/broker.xml:/var/lib/artemis-instance/etc-override/broker.xml:ro

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8161/console/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s


  my-artemis-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: messaging-artemis

    depends_on:
#      artemis:
#        condition: service_healthy
      postgres:
        condition: service_healthy

    volumes:
      - ./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar

    ports:
      - "8080:8080"

    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"

      OTEL_SERVICE_NAME: my-artemis-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none

      SPRING_ARTEMIS_BROKER_URL: tcp://artemis:61616

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vaudoise
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lambda
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

      SPRING_SQL_INIT_MODE: always
      SPRING_SQL_INIT_SCHEMA_LOCATIONS: classpath:/db/schema.sql
      SPRING_SQL_INIT_DATA_LOCATIONS: classpath:/db/data.sql

      SPRING_JMS_LISTENER_SESSION_TRANSACTED: "true"

      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"

    restart: unless-stopped


